[build-system]
requires = ["setuptools<72.2.0", "swig"]

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "python -c 'import Box2D; print(Box2D)' && pytest -vv --pyargs Box2D.tests"
# TODO
skip = "cp37-win32"
