[build-system]
requires = ["setuptools<72.2.0", "swig"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest -vv --pyargs Box2D.tests"
# TODO
skip = "cp37-win32"
