image: Visual Studio 2015

environment:
  global:
    REPO_DIR: pybox2d
    PACKAGE_NAME: Box2D
    BUILD_COMMIT: 2.3.10
    BUILD_DEPENDS: "swig"
    TEST_DEPENDS: "pytest"
    CONDA_CHANNEL: conda-forge

  matrix:
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      TEST_DEPENDS: "pytest==4.6"
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      TEST_DEPENDS: "pytest==4.6"
    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      BUILD_DEPENDS: "swig wheel"
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      BUILD_DEPENDS: "swig wheel"
    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda37"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

# matrix:
#     fast_finish: true

install:
    # Install miniconda and fix headers
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
    - conda info

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"

    - git clone --branch %BUILD_COMMIT% --recursive git://github.com/pybox2d/pybox2d.git pybox2d

build_script:
    # Install build requirements
    - conda create --yes -c %CONDA_CHANNEL% -n build_env python=%PYTHON_VERSION% %BUILD_DEPENDS%
    - activate build_env

    - which python
    - python -m pip install --upgrade pip wheel setuptools

    # build wheel:
    - cd %REPO_DIR%

    # sigh
    - sed -i -e "s/sirkne at gmail dot com/sirkne@gmail.com/" setup.py

    - python setup.py build --force
    - python setup.py bdist_wheel
    - ls dist/*

test_script:
    # create test env
    - conda create --yes -c %CONDA_CHANNEL% -n test_env python=%PYTHON_VERSION%
    - activate test_env

    # some issues with conda dependencies
    - pip install %TEST_DEPENDS%

    # install from wheel
    - pip install --no-index --find-links dist/ %PACKAGE_NAME%

    # run tests from install wheel
    - cd ..
    - python -c "import Box2D; print('Imported Box2D successfully')"
    - pytest -vv --pyargs Box2D.tests

after_test:
    - cmd: conda upgrade -y python
    - IF "%APPVEYOR_REPO_BRANCH%" == "master" (
          python -m pip install twine &&
          set HOME=%USERPROFILE% &&
          python -m twine upload --verbose pybox2d\dist\*.whl --repository-url https://upload.pypi.org/legacy/ -u %PYPI_USERNAME% -p %PYPI_PASSWORD%
      ) ELSE (
          echo Wrong branch - not pushing to PyPI
      )

artifacts:
    - path: pybox2d\dist\*
