name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: pybox2d/pybox2d
          ref: 2.3.10
          path: pybox2d

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install build requirements
        shell: bash -e {0}
        run: |
          cp patches/pyproject.toml pybox2d
          cp patches/setup-2.3.10.py pybox2d/setup.py
          sed -i -e 's/assertEquals/assertEqual/' pybox2d/library/Box2D/tests/test_joints.py
          grep assertEquals pybox2d/library/Box2D/tests/*.py || echo "No assertEquals found"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        working-directory: pybox2d
        env:
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./pybox2d/wheelhouse/*.whl
